language: android
android:
  components:
    - tools

    # The BuildTools version
    - build-tools-19.0.0

    # The SDK version
    - android-19

    # Additional components
    - extra-android-m2repository

    # emulator image
    - sys-img-armeabi-v7a-android-19

    # others
    - extra

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

notifications:
  email: false
  on_success: always
  on_failure: always
